# 定义阶段
stages:
  - install
  - build
  - deploy

# 缓存配置
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - apps/*/node_modules/
    - .turbo
    - .pnpm-store

# 安装依赖
install:
  stage: install
  script:
    - pnpm install

# 构建
build-all:
  stage: build
  script:
    - pnpm build:test

# 部署
deploy-base:
  stage: deploy
  script:
    - scp -r apps/base/dist/* user@host1:/path/to/base/
  only:
    changes:
      - apps/**/*
