# 测试环境部署
deploy-test:
  stage: deploy
  script:
    - pnpm install
    - pnpm build:test
  only:
    - develop

# OT环境部署  
deploy-ot:
  stage: deploy
  script:
    - pnpm install
    - pnpm build:ot
  only:
    - release

# 生产环境部署
deploy-prod:
  stage: deploy
  script:
    - pnpm install
    - pnpm build:online
  only:
    - master 
